language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8.11.2
  - '9'
script:
  - npm install
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^\d+\.\d+\.\d+$/
